port=0

interface=tap0
#interface=enp70s0

dhcp-range=192.168.10.100,192.168.10.200,12h

enable-tftp
tftp-root=/srv/tftp

# Detect iPXE
dhcp-match=set:ipxe,175

# If already in iPXE → send script
dhcp-boot=tag:ipxe,http://192.168.10.1/boot.ipxe

# Otherwise load iPXE first
dhcp-boot=undionly.kpxe

log-dhcp
